#!/bin/sh

source ~/emsdk_portable/emsdk_set_env.sh

for core in core/*
do
  emcc `find $core -name '*.bc' -print` -O3 -o $core/core.js -s RESERVED_FUNCTION_POINTERS=7 -s TOTAL_MEMORY=268435456 -s EXPORTED_FUNCTIONS=@exports.json -s SHELL_FILE="'`pwd`/shell.js'" -s NO_DYNAMIC_EXECUTION=1 --memory-init-file 0
  cp retro.js cjs.js amd.js $core
done
