#!/bin/sh

source ~/emsdk_portable/emsdk_set_env.sh

find . -name .DS_Store -delete

for core in core/*
do
  find $core -name '*.bc' -delete
  find $core -name '*.js' -delete
  find $core -name '*.o' -delete
  find $core -name '*.mem' -delete
done
