#!/usr/bin/env node

var denodeify = require('denodeify')
var fs = require('fs')
var npm = require('npm')
function getDirs() {
  if (process.argv.length > 2)
    return Promise.resolve(process.argv.slice(1))
  else
    return denodeify(fs.readdir)('core')
}
getDirs().then(function (cores) {
  return Promise.all(cores.map(function(core) {
    if (core[0] === '.')
      return
    return Promise.resolve().then(function() {
      return denodeify(npm.load)()
    }).then(function() {
      return denodeify(fs.writeFile)('core/' + core + '/package.json', JSON.stringify({
        name: core,
        version: require('../package.json').version,
        main: 'retro.js',
        homepage: 'https://github.com/matthewbauer/retrojs',
        files: ['retro.js', 'core.js']
        dependencies: {
        }
      }))
    }).then(function() {
      return denodeify(npm.commands.publish)(['core/' + core])
    }).then(function() {
      return denodeify(fs.unlink)('core/' + core + '/package.json')
    })
  }))
}).catch(console.error)
